name: Build Windows & Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3' # 可改成你项目需要的版本

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Windows exe
        run: flutter build windows --release

      - name: Upload Windows exe
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/*.exe

  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
